### ISSUE TITLE
Include DateTime in TextDateAnnotation

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/nlpsandbox-schemas#120]
Suppose I want to de-identify this note: `"The patient came in 11 Novemb"`. A particularly good date-annotator would correctly produce an annotation `[{start: 20, length: 2, text: "11", dateFormat: "DD"}, {start: 20: length: 23, text: "Novemb"}]`.

If someone wanted to use this annotation to de-identify the note (e.g. our `phi-deidentifier`) using a date offset, this would be very difficult to do. The de-identifier would have to replicate work that the annotator likely already did in order to determine that `"Novemb"` is equal to something we might abstractly represent as `{month: 11}`.

What if we add something new to the [`TextDateAnnotation`](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/d68240020c644060c64ddd379ff54ef293b2704e/openapi/commons/components/schemas/TextDateAnnotation.yaml#L7) schema that can contain structured data about the date represented in the annotation? E.g. add a property like:

```
date:
  type: object
  properties:
    year:
      type: int
    month:
      type: int
    day:
      type: int
```
